#:kivy 1.0

#:set height 30

TestCaseEntry:
    height:height

    target_input:target_input
    command_button:command_button
    arg_input:arg_input

    StackLayout:
        Button:
            id:command_button
            size_hint:0.25, 1
            text:"Command"
            on_press:root.show_commands(self)
        TextInput:
            id:target_input
            size_hint:0.5, 1
            text:"target"
        TextInput:
            id:arg_input
            size_hint:0.25, 1
            text:""
